---

- include: install.yml
  tags:
    - rsnapshot
    - rsnapshot_install

- include: config.yml
  tags:
    - rsnapshot
    - rsnapshot_config

- include: not-root.yml
  when: rsnapshot_master_host_user != 'root'
  tags:
    - rsnapshot
    - rsnapshot_config
